# Generated by Django 4.0.4 on 2022-07-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post'},
        ),
        migrations.AddField(
            model_name='post',
            name='publik',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
