# Generated by Django 4.0.4 on 2022-07-05 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_post_options_post_publik'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Citys',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='city',
        ),
    ]
