# Generated by Django 4.0.6 on 2022-07-13 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_post_adresmark_post_cordmark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'post'},
        ),
    ]
