# Generated by Django 4.0.4 on 2022-07-05 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_coment_post_remove_otvet_avtorid_remove_otvet_postid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nike',
        ),
    ]
