# Generated by Django 4.0.4 on 2022-07-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_profile_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coment',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='userphoto'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users'),
        ),
    ]
