# Generated by Django 4.0.4 on 2022-07-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_remove_post_cordmark_coordinat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinat',
            name='cord_X',
            field=models.FloatField(default=37.64),
        ),
        migrations.AlterField(
            model_name='coordinat',
            name='cord_Y',
            field=models.FloatField(default=55.76),
        ),
    ]
